### ISSUE TITLE
Lab 1 instruction incomplete - Deploy SAM

### ISSUE THREAD

**Issue by SvenBayer** [aws-samples/aws-serverless-saas-layers#12]
Deploying SAM in Lab 1 Step 2 is incomplete. The instructions or the script is missing that npm install needs to be executed in the order-manager and product-manager folders. This is quite user-unfriendly.

**Steps to reproduce**
User executes server-deploy.sh and follows instructions to set up Lambda functions.

**Expected Result**
Lambda functions should work and Lab 1 Step 3 should succeed.

**Actual result**
Lambda functions fail since dynamodb-doc is not found. The server-deploy.sh script and instructions do not mention anything of installing the resources locally before executing the script.

**Comment by peteraws** [comment]
updated server_deploy.sh to add 'npm install'
