### ISSUE TITLE
Hi! 

### ISSUE THREAD

**Issue by rmros** [aws-samples/aws-serverless-saas-layers#2]
is there any related documents that what are you doing here? like aws-saas-factory-bootcamp.
i like to know what is your solution when you are using serverless approach  inside saas layers,

thanks a lot :)

**Comment by rmros** [comment]
thanks man @anubhavynr :+1: 
thank youuu

**Comment by anubhavynr** [comment]
You are welcome... Yes, the documentation is updated now.
